apiVersion: v2
name: hello-world
description: Hello world test
type: application
version: 0.1.1
appVersion: "1.16.0"
maintainers:
  - name: jaimeph
    email: jhalcon@freepik.com
  - name: sergiotejon
    email: stejon@freepik.com
