apiVersion: v2
name: hello-world
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
maintainers:
  - name: jaimeph
    email: jhalcon@freepik.com
  - name: sergiotejon
    email: stejon@freepik.com
