apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "launcher.fullname" . }}
  labels:
    {{- include "launcher.labels" . | nindent 4 }}
data:
  namespace: |- 
    {{ .Values.namespaceResource | nindent 4 }}

  serviceAccount: |-
    {{ .Values.serviceAccountResource | nindent 4 }}
