{{- range .Values.listeners }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "launcher.fullnameShort" $ }}-{{ .name }}
  labels:
    {{- include "launcher.labels" $ | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .whitelist }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: el-{{ include "launcher.fullnameShort" $ }}-{{ .name }}
            port:
              number: 8080
        path: /{{ include "launcher.fullnameShort" $ }}-{{ .name }}
        pathType: Exact
---
{{- end }}