apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "launcher.serviceAccountName" . }}
  labels:
    {{- include "launcher.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "launcher.serviceAccountName" . }}
  labels:
    {{- include "launcher.labels" . | nindent 4 }}
rules:
- apiGroups:
  - tekton.dev
  - triggers.tekton.dev
  - networking.k8s.io
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "launcher.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "launcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "launcher.serviceAccountName" . }}
